language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ITKHalWIMbsXZbQVoPwaW6wWjEtsYweC+jq3dedxjXXikJWIuMImnkla4GdN42kA/4RalOf5v+miPwrfpI/THSU6YpmbpNt6W9zPp118b1hKlRMbcvbKKKy9LFBR/WDfSuQ9k+AEorfHXqys7AorOXXulyvT/3XV1YS3tZBHQ9d8brCBX7uo4jgdVHEa2NkW3jGwbSBR06Tz1qu+saP80fmrjEeKrcCmCtm7Laossiw5K7b4xJq9kpjdgcPQbhfsvtm8IL8hpPGpbv8txBef/Q3daeaPvRGMv25KSVXsz/Ek+8RBitnXhwF2zI50BrbizUGDe5haHM0KO5Bf6FE5YB1SuslHhjMreI3NUIVWBLvvIdhOuPtSfC8nR1hU1NqP/OW5zZ3JY2I712pF7ZjX8G/ln7KjjD3uzgrLWyRZFFguWgRAxJcmfNSohnt4BYYYFkYmPYie32SBwfFBLyEbTUVxecAJU6djlhEDlIA0J1FX2qzGhhM4WFooa59RshmILagG7/7wBZtIbeaHuDZ3KLhosqtY3WGhZy/+laZzCW5zWmR6y4gRF2DNDU8VlEf9R8kQ1hjcx6deOAXAmKk4L55QqAI1l1pu2AMZ1dIHLV+LBw6hYpIC6yN6+hWRDvl2D3S2lhLBOjbmm4t5mhCNZ+yashiAh9MRPsKNle76EE4="
   - CONF=unix

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "9fans/drawterm"
      description: "Build submitted via Travis CI"
    notification_email: 0intro@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: master

script:
  - make clean
  - make
